### ISSUE TITLE
[BUG] parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by threedliteguy** [BlazingDB/blazingsql#793]
**Describe the bug**
Crash when using example from:
https://blog.blazingdb.com/data-visualization-with-blazingsql-12095862eb73

**Steps/Code to reproduce bug**
run sample code [(attached)]([url](url
[s3-test.py.txt](https://github.com/BlazingDB/blazingsql/files/4777253/s3-test.py.txt)
))

**Expected behavior**
No illegal memory access exception.

**Environment overview (please complete the following information)**
 - Environment location: 
Bare metal conda
Python 3.7.7 (default, Mar 23 2020, 22:36:06) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Debian 10 CUDA 10.2

 - Method of cuDF install: 

conda install -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.7

**Environment details**
PATH=/opt/miniconda3/bin:/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin

**Additional context**
Code attached.  Other tests using blazingsql worked fine on this box.

Output:

listening: tcp://*:22758
2020-06-14T15:56:41Z|-78920688|TRACE|deregisterFileSystem: filesystem authority not found
CacheDataLocalFile: /tmp/.blazing-temp-D63WqK6ZgzRBOMd0kxS4CzTDNC69hqAn1vlzzPGIjU8ijs78nLFqpShVKo8Qkdmm.orc
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered
distributed.nanny - WARNING - Restarting worker
BlazingContext ready
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing

After crash, nvidia-smi shows below, main python process is hung:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN V             On   | 00000000:01:00.0 Off |                  N/A |
| 29%   43C    P8    26W / 250W |    640MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     31262      C   python                                       627MiB |
+-----------------------------------------------------------------------------+

```

First time I ran it, it created a number of .orc files in /tmp before crashing with above error.  Another time it gave:

listening: tcp://*:22170
BlazingContext ready
2020-06-14T16:59:14Z|-682139984|TRACE|deregisterFileSystem: filesystem authority not found
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
Unable to start CUDA Context
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/dask_cuda/initialize.py", line 108, in dask_setup
    numba.cuda.current_context()
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    return self._activate_context_for(0)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 169, in _activate_context_for
    newctx = gpu.get_primary_context()
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 529, in get_primary_context
    driver.cuDevicePrimaryCtxRetain(byref(hctx), self.id)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 295, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/opt/miniconda3/envs/py37/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 330, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [304] Call to cuDevicePrimaryCtxRetain results in CUDA_ERROR_OPERATING_SYSTEM
pure virtual method called
terminate called without an active exception

Edit:
Tried accessing the files locally instead of from s3 and reproduced same error. As soon as memory fills up or after several orc files created (varies) gets illegal memory access or worker dies.  If the worker restarts successfully it does not appear to process anything. Using non-dask/cluster version of BlazingContext it says 'Killed' as soon as it runs out of memory on the GPU.  Processing only one  input file works fine as it does not run out of memory.

**Comment by Christian8491** [comment]
Hi @threedliteguy,  if you still have those  `/tmp/.blazing-temp-*.orc`, please remove it. Coming soon this feature (removing those `/tmp/` files) will be merged in. I will try to reproduce this issue.

**Comment by Christian8491** [comment]
@threedliteguy I would like to comment you that now we have a better handle when only want to see few rows (normally when want to know how data looks like). Please for the first step use something like this:
`result = bc.sql('select * from taxi limit 10')`   # instead of  `bc.sql('select * from taxi').tail()`
And then continue with the normal flow.

Or just use  `bc.sql('select * from taxi').tail()` with a single parquet file. And for the next query (that uses `dropoff_x  dropoff_y`) use all the parquet files.

If that works for you, for now we can close the issue. Meanwhile I will continue reviewing the source of this problem.

**Comment by threedliteguy** [comment]
Same error using limit 10 with no tail():
bc.sql('select * from taxi limit 10')

listening: tcp://*:22498BlazingContext readyterminate called after throwing an instance of 'thrust::system::system_error'terminate called after throwing an instance of 'thrust::system::system_error'  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountereddistributed.nanny - WARNING - Restarting workerdistributed.nanny - WARNING - Worker process still alive after 3 seconds, killing



    On Tuesday, June 16, 2020, 12:22:03 PM CDT, Christian Córdova <notifications@github.com> wrote:  
 
 


@threedliteguy I would like to comment you that now we have a better handle when only want to see few rows (normally when want to know how data looks like). Please for the first step use something like this:
result = bc.sql('select * from taxi limit 10') # instead of bc.sql('select * from taxi').tail()
And then continue with the normal flow.

Or just use bc.sql('select * from taxi').tail() with a single parquet file. And for the next query (that uses dropoff_x dropoff_y) use all the parquet files.

If that works for you, for now we can close the issue. Meanwhile I will continue reviewing the source of this problem.

**Comment by Christian8491** [comment]
@threedliteguy  thanks for the answer. Could yo please provide us the logs?  You should find a new `/blazing_log/` folder in the same path you ran the `s3-test.py.txt` script and attach it here, or at least the file(s) with the name(s) ` RAL.*.log` ? These files help us to debbuging and get the source problem :)

**Comment by threedliteguy** [comment]
I don't see those files (it's running dask maybe that's why)  Attached are the dask-worker-space and algebra files.

    On Tuesday, June 16, 2020, 12:56:25 PM CDT, Christian Córdova <notifications@github.com> wrote:  
 
 


@threedliteguy thanks for the answer. Could yo please provide us the logs? You should find a new /blazing_log/ folder in the same path you ran the s3-test.py.txt script and attach it here, or at least the file(s) with the name(s)  RAL.*.log ? These files help us to debbuging and get the source problem :)

**Comment by Christian8491** [comment]
Hi @threedliteguy  only to let you know a fix was merged in recently. So  this issue should go away. Please, if you can run  again   `bc.sql('select * from taxi limit 10')` and verify whether the  issue was fixed or do you still have the same problem.

**Comment by threedliteguy** [comment]
Same issue.  I commented out the colorset and datashader code and just ran the blazingsql part on a fresh environment.
(py37) user@alien:~$conda create --name py37a python=3.7Collecting package metadata (current_repodata.json): doneSolving environment: done
## Package Plan ##
  environment location: /opt/miniconda3/envs/py37a
  added / updated specs:    - python=3.7

The following packages will be downloaded:
    package                    |            build    ---------------------------|-----------------    certifi-2020.4.5.2         |           py37_0         157 KB    libedit-3.1.20191231       |       h7b6447c_0         167 KB    pip-20.1.1                 |           py37_1         1.7 MB    setuptools-47.3.0          |           py37_0         522 KB    sqlite-3.32.2              |       h62c20be_0         1.1 MB    tk-8.6.10                  |       hbc83047_0         3.0 MB    ------------------------------------------------------------                                           Total:         6.6 MB
The following NEW packages will be INSTALLED:
  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0  certifi            pkgs/main/linux-64::certifi-2020.4.5.2-py37_0  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h7b6447c_0  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_1  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0  pip                pkgs/main/linux-64::pip-20.1.1-py37_1  python             pkgs/main/linux-64::python-3.7.7-hcff3b4d_5  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0  setuptools         pkgs/main/linux-64::setuptools-47.3.0-py37_0  sqlite             pkgs/main/linux-64::sqlite-3.32.2-h62c20be_0  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3

Proceed ([y]/n)? y

Downloading and Extracting Packagessqlite-3.32.2        | 1.1 MB    | ########################################################################################################### | 100% libedit-3.1.20191231 | 167 KB    | ########################################################################################################### | 100% tk-8.6.10            | 3.0 MB    | ########################################################################################################### | 100% certifi-2020.4.5.2   | 157 KB    | ########################################################################################################### | 100% setuptools-47.3.0    | 522 KB    | ########################################################################################################### | 100% pip-20.1.1           | 1.7 MB    | ########################################################################################################### | 100% Preparing transaction: doneVerifying transaction: doneExecuting transaction: done## To activate this environment, use##     $ conda activate py37a## To deactivate an active environment, use##     $ conda deactivate
(py37) user@alien:~$ conda activate py37a
(py37a) user@alien:~$ conda install -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.7Collecting package metadata (current_repodata.json): doneSolving environment: failed with initial frozen solve. Retrying with flexible solve.Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.Collecting package metadata (repodata.json): doneSolving environment: done
## Package Plan ##
  environment location: /opt/miniconda3/envs/py37a
  added / updated specs:    - blazingsql    - python=3.7

The following packages will be downloaded:
    package                    |            build    ---------------------------|-----------------    bokeh-2.1.0                |   py37hc8dfbb8_0         6.9 MB  conda-forge    brotlipy-0.7.0             |py37h8f50634_1000         346 KB  conda-forge    chardet-3.0.4              |py37hc8dfbb8_1006         169 KB  conda-forge    cryptography-2.9.2         |   py37hb09aad4_0         622 KB  conda-forge    freetype-2.10.2            |       he06d7ca_0         905 KB  conda-forge    idna-2.9                   |             py_1          52 KB  conda-forge    krb5-1.16.4                |       h2fd8d38_0         1.4 MB  conda-forge    libblas-3.8.0              |      14_openblas          10 KB  conda-forge    libcblas-3.8.0             |      14_openblas          10 KB  conda-forge    libgfortran-ng-7.5.0       |       hdf63c60_6         1.7 MB  conda-forge    liblapack-3.8.0            |      14_openblas          10 KB  conda-forge    libopenblas-0.3.7          |       h5ec1e0e_6         7.6 MB  conda-forge    libpng-1.6.37              |       hed695b0_1         308 KB  conda-forge    numba-0.49.1               |   py37h0da4684_0         3.5 MB  conda-forge    numpy-1.17.5               |   py37h95a1406_0         5.1 MB  conda-forge    olefile-0.46               |             py_0          31 KB  conda-forge    pillow-7.1.2               |   py37h718be6c_0         658 KB  conda-forge    pycparser-2.20             |             py_0          89 KB  conda-forge    pyopenssl-19.1.0           |             py_1          47 KB  conda-forge    pysocks-1.7.1              |   py37hc8dfbb8_1          27 KB  conda-forge    pyyaml-5.3.1               |   py37h8f50634_0         185 KB  conda-forge    requests-2.24.0            |     pyh9f0ad1d_0          47 KB  conda-forge    six-1.15.0                 |     pyh9f0ad1d_0          14 KB  conda-forge    snappy-1.1.8               |       he1b5a44_2          32 KB  conda-forge    urllib3-1.25.9             |             py_0          92 KB  conda-forge    yaml-0.2.5                 |       h516909a_0          82 KB  conda-forge    ------------------------------------------------------------                                           Total:        30.0 MB
The following NEW packages will be INSTALLED:
  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.15.0-py37h090bef1_2  blazingsql         blazingsql/label/cuda10.2/linux-64::blazingsql-0.14-cuda10.2_py37_949  bokeh              conda-forge/linux-64::bokeh-2.1.0-py37hc8dfbb8_0  boost-cpp          conda-forge/linux-64::boost-cpp-1.70.0-h8e57a91_2  brotli             conda-forge/linux-64::brotli-1.0.7-he1b5a44_1002  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py37h8f50634_1000  bsql-rapids-third~ blazingsql/linux-64::bsql-rapids-thirdparty-0.14.0-0  bsql-toolchain     blazingsql/linux-64::bsql-toolchain-0.14.0-0  bsql-toolchain-aw~ blazingsql/linux-64::bsql-toolchain-aws-cpp-0.14.0-0  bsql-toolchain-gc~ blazingsql/linux-64::bsql-toolchain-gcp-cpp-0.14.0-0  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2  c-ares             conda-forge/linux-64::c-ares-1.15.0-h516909a_1001  cffi               pkgs/main/linux-64::cffi-1.14.0-py37he30daa8_1  chardet            conda-forge/linux-64::chardet-3.0.4-py37hc8dfbb8_1006  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0  cloudpickle        conda-forge/noarch::cloudpickle-1.4.1-py_0  cppzmq             conda-forge/linux-64::cppzmq-4.6.0-hc9558a2_0  cryptography       conda-forge/linux-64::cryptography-2.9.2-py37hb09aad4_0  cudatoolkit        nvidia/linux-64::cudatoolkit-10.2.89-h6bb024c_0  cudf               rapidsai/linux-64::cudf-0.14.0-py37_0  cudnn              pkgs/main/linux-64::cudnn-7.6.5-cuda10.2_0  cupy               conda-forge/linux-64::cupy-7.5.0-py37h940342b_0  curl               conda-forge/linux-64::curl-7.68.0-hf8cf82a_0  cyrus-sasl         conda-forge/linux-64::cyrus-sasl-2.1.27-he38ecfd_0  cytoolz            conda-forge/linux-64::cytoolz-0.10.1-py37h516909a_0  dask               conda-forge/noarch::dask-2.18.1-py_0  dask-core          conda-forge/noarch::dask-core-2.18.1-py_0  dask-cuda          rapidsai/linux-64::dask-cuda-0.14.0-py37_0  dask-cudf          rapidsai/linux-64::dask-cudf-0.14.0-py37_0  distributed        conda-forge/linux-64::distributed-2.18.0-py37hc8dfbb8_0  dlpack             conda-forge/linux-64::dlpack-0.2-he1b5a44_1  double-conversion  conda-forge/linux-64::double-conversion-3.1.5-he1b5a44_2  fastavro           conda-forge/linux-64::fastavro-0.23.4-py37h8f50634_0  fastrlock          conda-forge/linux-64::fastrlock-0.5-py37h3340039_0  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0  fsspec             conda-forge/noarch::fsspec-0.7.4-py_0  future             conda-forge/linux-64::future-0.18.2-py37hc8dfbb8_1  gettext            conda-forge/linux-64::gettext-0.19.8.1-h5e8e0c9_1  gflags             conda-forge/linux-64::gflags-2.2.2-he1b5a44_1002  glog               conda-forge/linux-64::glog-0.4.0-h49b9bf7_3  grpc-cpp           conda-forge/linux-64::grpc-cpp-1.23.0-h18db393_0  gtest              conda-forge/linux-64::gtest-1.10.0-hc9558a2_2  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1  idna               conda-forge/noarch::idna-2.9-py_1  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0  jpeg               conda-forge/linux-64::jpeg-9d-h516909a_0  jpype1             conda-forge/linux-64::jpype1-0.7.5-py37h99015e2_0  krb5               conda-forge/linux-64::krb5-1.16.4-h2fd8d38_0  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas  libcudf            rapidsai/linux-64::libcudf-0.14.0-cuda10.2_0  libcurl            conda-forge/linux-64::libcurl-7.68.0-hda55be3_0  libevent           conda-forge/linux-64::libevent-2.1.10-h72c5cf5_0  libgcrypt          conda-forge/linux-64::libgcrypt-1.8.4-hf484d3e_1000  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6  libgpg-error       conda-forge/linux-64::libgpg-error-1.36-he1b5a44_0  libgsasl           conda-forge/linux-64::libgsasl-1.8.0-h19a2143_1004  libhdfs3           conda-forge/linux-64::libhdfs3-2.3-h311b756_1006  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas  libllvm8           conda-forge/linux-64::libllvm8-8.0.1-hc9558a2_0  libntlm            conda-forge/linux-64::libntlm-1.4-h516909a_1002  libnvstrings       rapidsai/linux-64::libnvstrings-0.14.0-cuda10.2_0  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1  libprotobuf        conda-forge/linux-64::libprotobuf-3.8.0-h8b12597_0  librmm             rapidsai/linux-64::librmm-0.14.0-cuda10.2_0  libsodium          conda-forge/linux-64::libsodium-1.0.17-h516909a_0  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_2  libtiff            conda-forge/linux-64::libtiff-4.1.0-hfc65ed5_0  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0  llvmlite           conda-forge/linux-64::llvmlite-0.32.1-py37h5202443_0  locket             conda-forge/noarch::locket-0.2.0-py_2  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py37h8f50634_1  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.0-py37h99015e2_1  nccl               conda-forge/linux-64::nccl-2.6.4.1-hc6a2c23_0  netifaces          conda-forge/linux-64::netifaces-0.10.9-py37h8f50634_1002  numba              conda-forge/linux-64::numba-0.49.1-py37h0da4684_0  numpy              conda-forge/linux-64::numpy-1.17.5-py37h95a1406_0  nvstrings          rapidsai/linux-64::nvstrings-0.14.0-py37_0  olefile            conda-forge/noarch::olefile-0.46-py_0  openjdk            conda-forge/linux-64::openjdk-8.0.192-h516909a_1005  packaging          conda-forge/noarch::packaging-20.4-pyh9f0ad1d_0  pandas             conda-forge/linux-64::pandas-0.25.3-py37hb3f55d8_0  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2  partd              conda-forge/noarch::partd-1.1.0-py_0  pillow             conda-forge/linux-64::pillow-7.1.2-py37h718be6c_0  psutil             conda-forge/linux-64::psutil-5.7.0-py37h8f50634_1  pyarrow            conda-forge/linux-64::pyarrow-0.15.0-py37h8b68381_1  pycparser          conda-forge/noarch::pycparser-2.20-py_0  pyhive             conda-forge/noarch::pyhive-0.6.2-pyh9f0ad1d_0  pynvml             conda-forge/noarch::pynvml-8.0.4-py_0  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0  pysocks            conda-forge/linux-64::pysocks-1.7.1-py37hc8dfbb8_1  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0  pyyaml             conda-forge/linux-64::pyyaml-5.3.1-py37h8f50634_0  re2                conda-forge/linux-64::re2-2020.04.01-he1b5a44_0  requests           conda-forge/noarch::requests-2.24.0-pyh9f0ad1d_0  rmm                rapidsai/linux-64::rmm-0.14.0-py37_0  sasl               conda-forge/linux-64::sasl-0.2.1-py37h3340039_1002  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_2  sortedcontainers   conda-forge/noarch::sortedcontainers-2.2.2-pyh9f0ad1d_0  spdlog             conda-forge/linux-64::spdlog-1.6.1-hc9558a2_0  sqlalchemy         conda-forge/linux-64::sqlalchemy-1.3.17-py37h8f50634_0  tblib              conda-forge/noarch::tblib-1.6.0-py_0  thrift             conda-forge/linux-64::thrift-0.13.0-py37h3340039_1  thrift-cpp         conda-forge/linux-64::thrift-cpp-0.12.0-hf3afdfd_1004  thrift_sasl        conda-forge/linux-64::thrift_sasl-0.4.2-py37h8f50634_0  toolz              conda-forge/noarch::toolz-0.10.0-py_0  tornado            conda-forge/linux-64::tornado-6.0.4-py37h8f50634_1  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.2-py_0  uriparser          conda-forge/linux-64::uriparser-0.9.3-he1b5a44_1  urllib3            conda-forge/noarch::urllib3-1.25.9-py_0  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0  zeromq             conda-forge/linux-64::zeromq-4.3.2-he1b5a44_2  zict               conda-forge/noarch::zict-2.0.0-py_0  zstd               conda-forge/linux-64::zstd-1.4.3-h3b9ef0a_0
The following packages will be UPDATED:
  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2020.4.5.2-hecda079_0
The following packages will be SUPERSEDED by a higher-priority channel:
  certifi              pkgs/main::certifi-2020.4.5.2-py37_0 --> conda-forge::certifi-2020.4.5.2-py37hc8dfbb8_0  openssl              pkgs/main::openssl-1.1.1g-h7b6447c_0 --> conda-forge::openssl-1.1.1g-h516909a_0

Proceed ([y]/n)? y

Downloading and Extracting Packagesbrotlipy-0.7.0       | 346 KB    | ########################################################################################################### | 100% pillow-7.1.2         | 658 KB    | ########################################################################################################### | 100% olefile-0.46         | 31 KB     | ########################################################################################################### | 100% snappy-1.1.8         | 32 KB     | ########################################################################################################### | 100% requests-2.24.0      | 47 KB     | ########################################################################################################### | 100% libopenblas-0.3.7    | 7.6 MB    | ########################################################################################################### | 100% pycparser-2.20       | 89 KB     | ########################################################################################################### | 100% liblapack-3.8.0      | 10 KB     | ########################################################################################################### | 100% numba-0.49.1         | 3.5 MB    | ########################################################################################################### | 100% freetype-2.10.2      | 905 KB    | ########################################################################################################### | 100% libgfortran-ng-7.5.0 | 1.7 MB    | ########################################################################################################### | 100% libcblas-3.8.0       | 10 KB     | ########################################################################################################### | 100% libblas-3.8.0        | 10 KB     | ########################################################################################################### | 100% libpng-1.6.37        | 308 KB    | ########################################################################################################### | 100% urllib3-1.25.9       | 92 KB     | ########################################################################################################### | 100% bokeh-2.1.0          | 6.9 MB    | ########################################################################################################### | 100% pyyaml-5.3.1         | 185 KB    | ########################################################################################################### | 100% chardet-3.0.4        | 169 KB    | ########################################################################################################### | 100% six-1.15.0           | 14 KB     | ########################################################################################################### | 100% idna-2.9             | 52 KB     | ########################################################################################################### | 100% pysocks-1.7.1        | 27 KB     | ########################################################################################################### | 100% cryptography-2.9.2   | 622 KB    | ########################################################################################################### | 100% krb5-1.16.4          | 1.4 MB    | ########################################################################################################### | 100% yaml-0.2.5           | 82 KB     | ########################################################################################################### | 100% numpy-1.17.5         | 5.1 MB    | ########################################################################################################### | 100% pyopenssl-19.1.0     | 47 KB     | ########################################################################################################### | 100% Preparing transaction: doneVerifying transaction: doneExecuting transaction: done
(py37a) user@alien:~$ python f2.py listening: tcp://*:18773BlazingContext readyterminate called after throwing an instance of 'thrust::system::system_error'terminate called after throwing an instance of 'thrust::system::system_error'  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered
distributed.nanny - WARNING - Restarting workerdistributed.nanny - WARNING - Worker process still alive after 3 seconds, killing

(py37a) user@alien:~$ cat f2.py# conda activate py37# conda install -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.7
from dask_cuda import LocalCUDAClusterfrom dask.distributed import Clientfrom blazingsql import BlazingContext#from colorcet import fire#from datashader import Canvas, transfer_functions as tf, utils

def main():
  cluster = LocalCUDACluster()  client = Client(cluster)

  bc = BlazingContext(dask_client=client, network_interface='lo')  #bc = BlazingContext()
  #bc.s3('bsql', bucket_name='blazingsql-colab')
  #files_10 = [f's3://bsql/taxi_parquet/yellow_tripdata_2010-0{i}.parquet' if i < 10   #            else f's3://bsql/taxi_parquet/yellow_tripdata_2010-{i}.parquet' for i in range(1, 13)]
  #files_11 = [f's3://bsql/taxi_parquet/yellow_tripdata_2011-0{i}.parquet' if i < 10   #            else f's3://bsql/taxi_parquet/yellow_tripdata_2011-{i}.parquet' for i in range(1, 13)]
  #f = files_10 + files_11   f = [f'/home/user/t/x{i}.parquet' for i in range(0,24)]  #f = [f'/home/user/t/x{i}.parquet' for i in range(0,1)]    bc.create_table('taxi', f)  bc.sql('select * from taxi limit 10')
  pi = 3.141592653589793  o_shift = 2 * pi * 6378137 / 2
  query = f'''        SELECT             dropoff_longitude * {o_shift} / 180 AS dropoff_x,             LOG10(TAN(((90 + dropoff_latitude) * {pi} / 360))) / {pi} / 180 * {o_shift} / 180 AS dropoff_y        FROM             taxi            WHERE                pickup_longitude < -73.75 AND pickup_longitude > -74.15                AND dropoff_longitude < -73.75 AND dropoff_longitude > -74.15                AND pickup_latitude > 40.68 AND pickup_latitude < 40.84                AND dropoff_latitude > 40.68 AND dropoff_latitude < 40.84                '''

  agg = Canvas().points(bc.sql(query), 'dropoff_x', 'dropoff_y')  print('done with agg.')
  #img = tf.set_background(tf.shade(agg, cmap=fire), "black")
  #utils.export_image(img=img,filename='fire.png', fmt=".png", background=None)
  print('done')
if __name__ == '__main__':       main()







    On Thursday, June 18, 2020, 06:02:12 PM CDT, Christian Córdova <notifications@github.com> wrote:  
 
 


Hi @threedliteguy only to let you know a fix was merged in recently. So this issue should go away. Please, if you can run again bc.sql('select * from taxi limit 10') and verify whether the issue was fixed or do you still have the same problem.

**Comment by Christian8491** [comment]
Thanks for proof that. I have an thought what is happening. I will send a new fix and I let you know when is ready to try again.

**Comment by Christian8491** [comment]
Hi @threedliteguy  only to let you know a fix was merged in in these days. I hope you can verified it whether you still need.

**Comment by threedliteguy** [comment]
Same error with latest code:
listening: tcp://*:26257BlazingContext readyCacheDataLocalFile: /tmp/.blazing-temp-cKzfBOm50VT8CQHNbz8hJbF9cyOq4DwkOKzoNU3OuSMub2vXIz6p8AIiDLL2IYIF.orcterminate called after throwing an instance of 'thrust::system::system_error'terminate called after throwing an instance of 'thrust::system::system_error'  what():  for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered  what():  for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountereddistributed.nanny - WARNING - Restarting worker

$ conda list# packages in environment at /opt/miniconda3/envs/py37b:## Name                    Version                   Build  Channel_libgcc_mutex             0.1                        main  arrow-cpp                 0.15.0           py37h090bef1_2    conda-forgeblazingsql                0.14            cuda10.2_py37_949    blazingsql/label/cuda10.2bokeh                     2.1.1            py37hc8dfbb8_0    conda-forgeboost-cpp                 1.70.0               h8e57a91_2    conda-forgebrotli                    1.0.7             he1b5a44_1002    conda-forgebrotlipy                  0.7.0           py37h8f50634_1000    conda-forgebsql-rapids-thirdparty    0.14.0                        0    blazingsqlbsql-toolchain            0.14.0                        0    blazingsqlbsql-toolchain-aws-cpp    0.14.0                        0    blazingsqlbsql-toolchain-gcp-cpp    0.14.0                        0    blazingsqlbzip2                     1.0.8                h516909a_2    conda-forgec-ares                    1.15.0            h516909a_1001    conda-forgeca-certificates           2020.6.20            hecda079_0    conda-forgecertifi                   2020.6.20        py37hc8dfbb8_0    conda-forgecffi                      1.14.0           py37he30daa8_1  chardet                   3.0.4           py37hc8dfbb8_1006    conda-forgeclick                     7.1.2              pyh9f0ad1d_0    conda-forgecloudpickle               1.4.1                      py_0    conda-forgecppzmq                    4.6.0                hc9558a2_0    conda-forgecryptography              2.9.2            py37hb09aad4_0    conda-forgecudatoolkit               10.2.89              h6bb024c_0    nvidiacudf                      0.14.0                   py37_0    rapidsaicudnn                     7.6.5                cuda10.2_0  cupy                      7.5.0            py37h940342b_0    conda-forgecurl                      7.68.0               hf8cf82a_0    conda-forgecyrus-sasl                2.1.27               he38ecfd_0    conda-forgecytoolz                   0.10.1           py37h516909a_0    conda-forgedask                      2.19.0                     py_0    conda-forgedask-core                 2.19.0                     py_0    conda-forgedask-cuda                 0.14.1                   py37_0    rapidsaidask-cudf                 0.14.0                   py37_0    rapidsaidistributed               2.19.0           py37hc8dfbb8_0    conda-forgedlpack                    0.2                  he1b5a44_1    conda-forgedouble-conversion         3.1.5                he1b5a44_2    conda-forgefastavro                  0.23.5           py37h8f50634_0    conda-forgefastrlock                 0.5              py37h3340039_0    conda-forgefreetype                  2.10.2               he06d7ca_0    conda-forgefsspec                    0.7.4                      py_0    conda-forgefuture                    0.18.2           py37hc8dfbb8_1    conda-forgegettext                   0.19.8.1             h5e8e0c9_1    conda-forgegflags                    2.2.2             he1b5a44_1002    conda-forgeglog                      0.4.0                h49b9bf7_3    conda-forgegrpc-cpp                  1.23.0               h18db393_0    conda-forgegtest                     1.10.0               hc9558a2_2    conda-forgeheapdict                  1.0.1                      py_0    conda-forgeicu                       64.2                 he1b5a44_1    conda-forgeidna                      2.9                        py_1    conda-forgejinja2                    2.11.2             pyh9f0ad1d_0    conda-forgejpeg                      9d                   h516909a_0    conda-forgejpype1                    0.7.5            py37h99015e2_0    conda-forgekrb5                      1.16.4               h2fd8d38_0    conda-forgeld_impl_linux-64          2.33.1               h53a641e_7  libblas                   3.8.0               14_openblas    conda-forgelibcblas                  3.8.0               14_openblas    conda-forgelibcudf                   0.14.0               cuda10.2_0    rapidsailibcurl                   7.68.0               hda55be3_0    conda-forgelibedit                   3.1.20191231         h7b6447c_0  libevent                  2.1.10               hcdb4288_1    conda-forgelibffi                    3.3                  he6710b0_1  libgcc-ng                 9.1.0                hdf63c60_0  libgcrypt                 1.8.4             hf484d3e_1000    conda-forgelibgfortran-ng            7.5.0                hdf63c60_6    conda-forgelibgpg-error              1.36                 he1b5a44_0    conda-forgelibgsasl                  1.8.0             h19a2143_1004    conda-forgelibhdfs3                  2.3               h311b756_1006    conda-forgelibiconv                  1.15              h516909a_1006    conda-forgeliblapack                 3.8.0               14_openblas    conda-forgelibllvm8                  8.0.1                hc9558a2_0    conda-forgelibntlm                   1.4               h516909a_1002    conda-forgelibnvstrings              0.14.0               cuda10.2_0    rapidsailibopenblas               0.3.7                h5ec1e0e_6    conda-forgelibpng                    1.6.37               hed695b0_1    conda-forgelibprotobuf               3.8.0                h8b12597_0    conda-forgelibrmm                    0.14.0               cuda10.2_0    rapidsailibsodium                 1.0.17               h516909a_0    conda-forgelibssh2                   1.9.0                hab1572f_2    conda-forgelibstdcxx-ng              9.1.0                hdf63c60_0  libtiff                   4.1.0                hfc65ed5_0    conda-forgelibuuid                   2.32.1            h14c3975_1000    conda-forgelibxml2                   2.9.10               hee79883_0    conda-forgellvmlite                  0.32.1           py37h5202443_0    conda-forgelocket                    0.2.0                      py_2    conda-forgelz4-c                     1.8.3             he1b5a44_1001    conda-forgemarkupsafe                1.1.1            py37h8f50634_1    conda-forgemsgpack-python            1.0.0            py37h99015e2_1    conda-forgenccl                      2.7.3.1              hc6a2c23_0    conda-forgencurses                   6.2                  he6710b0_1  netifaces                 0.10.9          py37h8f50634_1002    conda-forgenumba                     0.49.1           py37h0da4684_0    conda-forgenumpy                     1.17.5           py37h95a1406_0    conda-forgenvstrings                 0.14.0                   py37_0    rapidsaiolefile                   0.46                       py_0    conda-forgeopenjdk                   8.0.192           h516909a_1005    conda-forgeopenssl                   1.1.1g               h516909a_0    conda-forgepackaging                 20.4               pyh9f0ad1d_0    conda-forgepandas                    0.25.3           py37hb3f55d8_0    conda-forgeparquet-cpp               1.5.1                         2    conda-forgepartd                     1.1.0                      py_0    conda-forgepillow                    7.1.2            py37h718be6c_0    conda-forgepip                       20.1.1                   py37_1  psutil                    5.7.0            py37h8f50634_1    conda-forgepyarrow                   0.15.0           py37h8b68381_1    conda-forgepycparser                 2.20                       py_0    conda-forgepyhive                    0.6.2              pyh9f0ad1d_0    conda-forgepynvml                    8.0.4                      py_0    conda-forgepyopenssl                 19.1.0                     py_1    conda-forgepyparsing                 2.4.7              pyh9f0ad1d_0    conda-forgepysocks                   1.7.1            py37hc8dfbb8_1    conda-forgepython                    3.7.7                hcff3b4d_5  python-dateutil           2.8.1                      py_0    conda-forgepython_abi                3.7                     1_cp37m    conda-forgepytz                      2020.1             pyh9f0ad1d_0    conda-forgepyyaml                    5.3.1            py37h8f50634_0    conda-forgere2                       2020.04.01           he1b5a44_0    conda-forgereadline                  8.0                  h7b6447c_0  requests                  2.24.0             pyh9f0ad1d_0    conda-forgermm                       0.14.0                   py37_0    rapidsaisasl                      0.2.1           py37h3340039_1002    conda-forgesetuptools                47.3.1                   py37_0  six                       1.15.0             pyh9f0ad1d_0    conda-forgesnappy                    1.1.8                he1b5a44_2    conda-forgesortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forgespdlog                    1.6.1                hc9558a2_0    conda-forgesqlalchemy                1.3.17           py37h8f50634_0    conda-forgesqlite                    3.32.3               h62c20be_0  tblib                     1.6.0                      py_0    conda-forgethrift                    0.13.0           py37h3340039_1    conda-forgethrift-cpp                0.12.0            hf3afdfd_1004    conda-forgethrift_sasl               0.4.2            py37h8f50634_0    conda-forgetk                        8.6.10               hbc83047_0  toolz                     0.10.0                     py_0    conda-forgetornado                   6.0.4            py37h8f50634_1    conda-forgetyping_extensions         3.7.4.2                    py_0    conda-forgeuriparser                 0.9.3                he1b5a44_1    conda-forgeurllib3                   1.25.9                     py_0    conda-forgewheel                     0.34.2                   py37_0  xz                        5.2.5                h7b6447c_0  yaml                      0.2.5                h516909a_0    conda-forgezeromq                    4.3.2                he1b5a44_2    conda-forgezict                      2.0.0                      py_0    conda-forgezlib                      1.2.11               h7b6447c_3  zstd                      1.4.3                h3b9ef0a_0    conda-forge



    On Wednesday, June 24, 2020, 05:56:03 PM CDT, Christian Córdova <notifications@github.com> wrote:  
 
 


Hi @threedliteguy only to let you know a fix was merged in in these days. I hope you can verified it whether you still need.

**Comment by Christian8491** [comment]
I see you are using 0.14 (and some dependencies from that). So, changes were merged in to branch-0.15.  I suggest you to try with the nightly version of BlazingSQL (0.15). If you  have issues building this let me know. As well I suggest you create a new conda environment to work with 0.15 branch.

**Comment by threedliteguy** [comment]
I used nightly this time in a fresh conda env.It seems to hang without using much memory on GPU (stays at 973MiB / 12066MiB ) or cpu activity:

conda create --name py37c python=3.7conda activate py37cconda install -c blazingsql-nightly/label/cuda10.2 -c blazingsql-nightly -c rapidsai-nightly -c nvidia -c conda-forge -c defaults blazingsql python=3.7


$ python f2.py listening: tcp://*:17110WARNING: An illegal reflective access operation has occurredWARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/opt/miniconda3/envs/py37c/lib/blazingsql-algebra.jar) to field java.nio.Buffer.addressWARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtilWARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operationsWARNING: All illegal access operations will be denied in a future releaseBlazingContext readydistributed.nanny - WARNING - Restarting worker


In separate window:
$ watch nvidia-smi Thu Jun 25 08:05:53 2020       +-----------------------------------------------------------------------------+| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     ||-------------------------------+----------------------+----------------------+| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC || Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. ||===============================+======================+======================||   0  TITAN V             On   | 00000000:01:00.0 Off |                  N/A || 31%   45C    P8    26W / 250W |    973MiB / 12066MiB |      0%      Default |+-------------------------------+----------------------+----------------------+                                                                               +-----------------------------------------------------------------------------+| Processes:                                                       GPU Memory ||  GPU       PID   Type   Process name                             Usage      ||=============================================================================||    0      9320      C   python                                       639MiB ||    0      9492      C   /opt/miniconda3/envs/py37c/bin/python        305MiB |+-----------------------------------------------------------------------------+

Tasks: 160 total,   1 running, 159 sleeping,   0 stopped,   0 zombie%Cpu(s):  1.3 us,  3.1 sy,  0.0 ni, 95.4 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 stMiB Mem :  15944.8 total,  13292.4 free,   1713.8 used,    938.5 buff/cacheMiB Swap:  16286.0 total,  16245.6 free,     40.4 used.  13907.0 avail Mem 
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                            587 root      20   0       0      0      0 S  22.9   0.0   1779:46 nv_queue                                                                          9320 user      20   0   16.2g   1.3g 466124 S   5.6   8.6   0:32.23 python                                                                            9492 user      20   0   14.9g 479672 287676 S   5.3   2.9   0:27.18 python                                                                             585 root     -51   0       0      0      0 S   0.7   0.0  52:20.07 irq/144-nvidia                                 
$ conda list# packages in environment at /opt/miniconda3/envs/py37c:## Name                    Version                   Build  Channel_libgcc_mutex             0.1                        main  abseil-cpp                20200225.2           he1b5a44_0    conda-forgealsa-lib                  1.1.5             h516909a_1002    conda-forgearrow-cpp                 0.17.1          py37h1234567_8_cuda    conda-forgearrow-cpp-proc            1.0.0                      cuda    conda-forgeaws-sdk-cpp               1.7.164              hc831370_1    conda-forgeblazingsql                0.15.0a         cuda10.2_py37_101    blazingsql-nightly/label/cuda10.2bokeh                     2.1.1            py37hc8dfbb8_0    conda-forgeboost-cpp                 1.72.0               h7b93d67_1    conda-forgebrotli                    1.0.7             he1b5a44_1002    conda-forgebrotlipy                  0.7.0           py37h8f50634_1000    conda-forgebzip2                     1.0.8                h516909a_2    conda-forgec-ares                    1.15.0            h516909a_1001    conda-forgeca-certificates           2020.6.20            hecda079_0    conda-forgecertifi                   2020.6.20        py37hc8dfbb8_0    conda-forgecffi                      1.14.0           py37he30daa8_1  chardet                   3.0.4           py37hc8dfbb8_1006    conda-forgeclick                     7.1.2              pyh9f0ad1d_0    conda-forgecloudpickle               1.4.1                      py_0    conda-forgecppzmq                    4.6.0                hc9558a2_0    conda-forgecryptography              2.9.2            py37hb09aad4_0    conda-forgecudatoolkit               10.2.89              h6bb024c_0    nvidiacudf                      0.15.0a200625   py37_gf52f04291_1773    rapidsai-nightlycudnn                     7.6.5                cuda10.2_0  cupy                      7.5.0            py37h940342b_0    conda-forgecurl                      7.71.0               he644dc0_0    conda-forgecyrus-sasl                2.1.27               h063b49f_1    conda-forgecytoolz                   0.10.1           py37h516909a_0    conda-forgedask                      2.19.0                     py_0    conda-forgedask-core                 2.19.0                     py_0    conda-forgedask-cuda                 0.15.0a200625           py37_43    rapidsai-nightlydask-cudf                 0.15.0a200625   py37_gf52f04291_1773    rapidsai-nightlydistributed               2.19.0           py37hc8dfbb8_0    conda-forgedlpack                    0.2                  he1b5a44_1    conda-forgedouble-conversion         3.1.5                he1b5a44_2    conda-forgefastavro                  0.23.5           py37h8f50634_0    conda-forgefastrlock                 0.5              py37h3340039_0    conda-forgefontconfig                2.13.1            h1056068_1002    conda-forgefreetype                  2.10.2               he06d7ca_0    conda-forgefsspec                    0.7.4                      py_0    conda-forgefuture                    0.18.2           py37hc8dfbb8_1    conda-forgegflags                    2.2.2             he1b5a44_1002    conda-forgegiflib                    5.2.1                h516909a_2    conda-forgeglog                      0.4.0                h49b9bf7_3    conda-forgegoogle-cloud-cpp          1.14.0               h3bc3856_2    conda-forgegoogle-cloud-cpp-common   0.25.0               h6a85093_6    conda-forgegoogleapis-cpp            0.10.0               h52dead3_2    conda-forgegrpc-cpp                  1.30.0               h9ea6770_0    conda-forgegtest                     1.10.0               hc9558a2_2    conda-forgeheapdict                  1.0.1                      py_0    conda-forgeicu                       67.1                 he1b5a44_0    conda-forgeidna                      2.9                        py_1    conda-forgejinja2                    2.11.2             pyh9f0ad1d_0    conda-forgejpeg                      9d                   h516909a_0    conda-forgejpype1                    0.7.5            py37h99015e2_0    conda-forgekrb5                      1.17.1               hfafb76e_1    conda-forgelcms2                     2.11                 hbd6801e_0    conda-forgeld_impl_linux-64          2.33.1               h53a641e_7  libblas                   3.8.0               14_openblas    conda-forgelibcblas                  3.8.0               14_openblas    conda-forgelibcrc32c                 1.1.1                he1b5a44_0    conda-forgelibcudf                   0.15.0a200625   cuda10.2_gf52f04291_1773    rapidsai-nightlylibcurl                   7.71.0               hcdd3856_0    conda-forgelibedit                   3.1.20191231         h7b6447c_0  libevent                  2.1.10               hcdb4288_1    conda-forgelibffi                    3.3                  he6710b0_1  libgcc-ng                 9.1.0                hdf63c60_0  libgfortran-ng            7.5.0                hdf63c60_6    conda-forgelibiconv                  1.15              h516909a_1006    conda-forgeliblapack                 3.8.0               14_openblas    conda-forgelibllvm8                  8.0.1                hc9558a2_0    conda-forgelibntlm                   1.4               h516909a_1002    conda-forgelibopenblas               0.3.7                h5ec1e0e_6    conda-forgelibpng                    1.6.37               hed695b0_1    conda-forgelibprotobuf               3.12.3               h8b12597_0    conda-forgelibrmm                    0.15.0a200625   cuda10.2_g8f30a6a_219    rapidsai-nightlylibsodium                 1.0.17               h516909a_0    conda-forgelibssh2                   1.9.0                hab1572f_2    conda-forgelibstdcxx-ng              9.1.0                hdf63c60_0  libtiff                   4.1.0                hc7e4089_6    conda-forgelibuuid                   2.32.1            h14c3975_1000    conda-forgelibwebp-base              1.1.0                h516909a_3    conda-forgelibxcb                    1.13              h14c3975_1002    conda-forgelibxml2                   2.9.10               h72b56ed_1    conda-forgellvmlite                  0.32.1           py37h5202443_0    conda-forgelocket                    0.2.0                      py_2    conda-forgelz4-c                     1.9.2                he1b5a44_1    conda-forgemarkupsafe                1.1.1            py37h8f50634_1    conda-forgemsgpack-python            1.0.0            py37h99015e2_1    conda-forgenccl                      2.7.3.1              hc6a2c23_0    conda-forgencurses                   6.2                  he6710b0_1  netifaces                 0.10.9          py37h8f50634_1002    conda-forgenumba                     0.49.1           py37h0da4684_0    conda-forgenumpy                     1.17.5           py37h95a1406_0    conda-forgeolefile                   0.46                       py_0    conda-forgeopenjdk                   11.0.1            h600c080_1018    conda-forgeopenssl                   1.1.1g               h516909a_0    conda-forgepackaging                 20.4               pyh9f0ad1d_0    conda-forgepandas                    0.25.3           py37hb3f55d8_0    conda-forgeparquet-cpp               1.5.1                         2    conda-forgepartd                     1.1.0                      py_0    conda-forgepillow                    7.1.2            py37h718be6c_0    conda-forgepip                       20.1.1                   py37_1  psutil                    5.7.0            py37h8f50634_1    conda-forgepthread-stubs             0.4               h14c3975_1001    conda-forgepyarrow                   0.17.1          py37h1234567_8_cuda    conda-forgepycparser                 2.20                       py_0    conda-forgepyhive                    0.6.2              pyh9f0ad1d_0    conda-forgepynvml                    8.0.4                      py_0    conda-forgepyopenssl                 19.1.0                     py_1    conda-forgepyparsing                 2.4.7              pyh9f0ad1d_0    conda-forgepysocks                   1.7.1            py37hc8dfbb8_1    conda-forgepython                    3.7.7                hcff3b4d_5  python-dateutil           2.8.1                      py_0    conda-forgepython_abi                3.7                     1_cp37m    conda-forgepytz                      2020.1             pyh9f0ad1d_0    conda-forgepyyaml                    5.3.1            py37h8f50634_0    conda-forgere2                       2020.06.01           he1b5a44_0    conda-forgereadline                  8.0                  h7b6447c_0  requests                  2.24.0             pyh9f0ad1d_0    conda-forgermm                       0.15.0a200625   py37_g8f30a6a_219    rapidsai-nightlysasl                      0.2.1           py37h3340039_1002    conda-forgesetuptools                47.3.1                   py37_0  six                       1.15.0             pyh9f0ad1d_0    conda-forgesnappy                    1.1.8                he1b5a44_2    conda-forgesortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forgespdlog                    1.6.1                hc9558a2_0    conda-forgesqlalchemy                1.3.17           py37h8f50634_0    conda-forgesqlite                    3.32.3               h62c20be_0  tblib                     1.6.0                      py_0    conda-forgethrift                    0.13.0           py37h3340039_1    conda-forgethrift-cpp                0.13.0               h62aa4f2_2    conda-forgethrift_sasl               0.4.2            py37h8f50634_0    conda-forgetk                        8.6.10               hbc83047_0  toolz                     0.10.0                     py_0    conda-forgetornado                   6.0.4            py37h8f50634_1    conda-forgetyping_extensions         3.7.4.2                    py_0    conda-forgeurllib3                   1.25.9                     py_0    conda-forgewheel                     0.34.2                   py37_0  xorg-fixesproto           5.0               h14c3975_1002    conda-forgexorg-inputproto           2.3.2             h14c3975_1002    conda-forgexorg-kbproto              1.0.7             h14c3975_1002    conda-forgexorg-libx11               1.6.9                h516909a_0    conda-forgexorg-libxau               1.0.9                h14c3975_0    conda-forgexorg-libxdmcp             1.1.3                h516909a_0    conda-forgexorg-libxext              1.3.4                h516909a_0    conda-forgexorg-libxfixes            5.0.3             h516909a_1004    conda-forgexorg-libxi                1.7.10               h516909a_0    conda-forgexorg-libxrender           0.9.10            h516909a_1002    conda-forgexorg-libxtst              1.2.3             h516909a_1002    conda-forgexorg-recordproto          1.14.2            h516909a_1002    conda-forgexorg-renderproto          0.11.1            h14c3975_1002    conda-forgexorg-xextproto            7.3.0             h14c3975_1002    conda-forgexorg-xproto               7.0.31            h14c3975_1007    conda-forgexz                        5.2.5                h7b6447c_0  yaml                      0.2.5                h516909a_0    conda-forgezeromq                    4.3.2                he1b5a44_2    conda-forgezict                      2.0.0                      py_0    conda-forgezlib                      1.2.11               h7b6447c_3  zstd                      1.4.4                h6597ccf_3    conda-forge



    On Wednesday, June 24, 2020, 08:03:05 PM CDT, Christian Córdova <notifications@github.com> wrote:  
 
 


I see you are using 0.14 (and some dependencies from that). So, changes were merged in to branch-0.15. I suggest you to try with the nightly version of BlazingSQL (0.15). If you have issues building this let me know. As well I suggest you create a new conda environment to work with 0.15 branch.

**Comment by Christian8491** [comment]
It looks like you have an issue related to your java version.  Could you try this   `conda list | grep jdk ` in this environment. 
Also could you only run the second query? ` SELECT  dropoff_longitude * {o_shift} / 180 AS dropoff_x,....` and waiting a while, remember this file come from s3.

**Comment by threedliteguy** [comment]
It did not have a conda package for openjdk listed, so i installed it, then it seemed to run though without error. 
Fyi, with jdk 8 it gave no WARNs, but jdk 11 it gave (but still ran to end ok):WARNING: An illegal reflective access operation has occurredWARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/opt/miniconda3/envs/py37g/lib/blazingsql-algebra.jar) to field java.nio.Buffer.addressWARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtilWARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operationsWARNING: All illegal access operations will be denied in a future release
However then once i tried to :
conda install colorcet datashader
to run the full example, there were a LOT of incompatible libs.



    On Thursday, June 25, 2020, 11:08:08 AM CDT, Christian Córdova <notifications@github.com> wrote:  
 
 


It looks like you have an issue related to your java version. Could you try this conda list | grep jdk  in this environment.
Also could you only run the second query?  SELECT dropoff_longitude * {o_shift} / 180 AS dropoff_x,.... and waiting a while, remember this file come from s3.

**Comment by Christian8491** [comment]
I do not know about `datashader`, but I suppose you should review the versions it offers and their compatibility with `jdk` if they exist.
